# Prior to conda-forge, Copyright 2018-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "epoxy" %}
{% set version = "1.5.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anholt/libepoxy/archive/refs/tags/{{ version }}.tar.gz
  sha256: a7ced37f4102b745ac86d6a70a9da399cc139ff168ba6b8002b4d8d43c900c15

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('epoxy', max_pin='x.x') }}

requirements:
  build:
    - meson
    - ninja-base
    - pkg-config
    - pthread-stubs  # [linux]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - libdrm                    # [linux]
    - libegl-devel              # [linux]
    - libgl-devel               # [linux]
    - libglx-devel              # [linux]
    - xorg-libx11               # [linux]
    - xorg-libxdamage           # [linux]
    - xorg-libxext              # [linux]
    - xorg-libxfixes            # [linux]
    - xorg-libxxf86vm           # [linux]

test:
  requires:
    - pkg-config
    - libegl-devel  # [linux]
    - libgl-devel   # [linux]
    - libglx-devel  # [linux]
  commands:
    - test -f $PREFIX/include/epoxy/common.h         # [unix]
    - test -f $PREFIX/include/epoxy/egl.h            # [linux]
    - test -f $PREFIX/include/epoxy/egl_generated.h  # [linux]
    - test -f $PREFIX/include/epoxy/gl.h             # [unix]
    - test -f $PREFIX/include/epoxy/gl_generated.h   # [unix]
    - test -f $PREFIX/include/epoxy/glx.h            # [linux]
    - test -f $PREFIX/include/epoxy/glx_generated.h  # [linux]
    - test -f $PREFIX/lib/libepoxy${SHLIB_EXT}       # [unix]
    - if not exist %PREFIX%\\Library\\include\\epoxy\\common.h exit 1         # [win]
    - if not exist %PREFIX%\\Library\\include\\epoxy\\gl.h exit 1             # [win]
    - if not exist %PREFIX%\\Library\\include\\epoxy\\gl_generated.h exit 1   # [win]
    - if not exist %PREFIX%\\Library\\include\\epoxy\\wgl.h exit 1            # [win]
    - if not exist %PREFIX%\\Library\\include\\epoxy\\wgl_generated.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\epoxy-0.dll exit 1                 # [win]
    - if not exist %PREFIX%\\Library\\lib\\epoxy.lib exit 1                   # [win]
    - pkg-config --debug --exists epoxy
    - pkg-config --validate epoxy

about:
  home: https://github.com/anholt/libepoxy
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'A library for handling OpenGL function pointer management for you.'
  description: |
    Epoxy is a library for handling OpenGL function pointer management for you.

    It hides the complexity of dlopen(), dlsym(), glXGetProcAddress(),
    eglGetProcAddress(), etc. from the app developer, with very little
    knowledge needed on their part. They get to read GL specs and write code
    using undecorated function names like glCompileShader().

    Don't forget to check for your extensions or versions being present before
    you use them, just like before! We'll tell you what you forgot to check
    for instead of just segfaulting, though.
  dev_url: https://github.com/anholt/libepoxy

extra:
  recipe-maintainers:
    - ryanvolz
    - stuarteberg
    - tschoonj
